services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      VITE_API_URL: ${VITE_API_URL}

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI : ${MONGO_URI}
      CORS_ORIGIN: ${CORS_ORIGIN}
